meta:
  url:
  name: Web slide with fusuma and figma
  author: quramy
  thumbnail:
  description: Web slide with fusuma and figma
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: false
  isVertical: false
  code:
    languages:
      - javascript
      - typescript
    plugins: []
    theme: default
extends:
  js:
  css: styles.css
